dataeng:
  outputs:
    dev:
      type: duckdb
      path: /home/ec2-user/dataeng/dataeng.duckdb
      extensions:
        - httpfs
        - aws
      secrets:
        - type: s3
          provider: credential_chain
  target: dev
