dataeng:
  outputs:
    default:
      type: duckdb
      path: /path/to/your/duckdb/file
      extensions:
        - httpfs
        - aws
      secrets:
        - type: s3
          provider: credential_chain
      target: default
