version: 2

sources:
  - name: staging
    tables:
      - name: cities
        config:
          external_location: "s3://dataeng-duckdb-dbt/worldcities.csv"
      - name: international_education_costs
        config:
          external_location: "s3://dataeng-duckdb-dbt/International_Education_Costs.csv"
