version: 2

sources:
  - name: raw_data
    tables:
      - name: cities
        config:
          external_location: "s3://dataeng-duckdb-dbt/worldcities.csv"
      - name: eduction
        config:
          external_location: "s3://dataeng-duckdb-dbt/International_Education_Costs.csv"
